---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Add Docker repository
      yum_repository:
        name: docker
        description: Docker edge Repository
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes

    - name: Install Docker
      yum:
        name: docker-ce
        enablerepo: docker
        update_cache: true
        state: present

    - name: Start and enable the docker daemon
      systemd:
        name: docker
        enabled: yes
        daemon_reload: yes
        state: started

    - name: Create daemon.json for cgroups
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Create docker user group
      group:
        name: docker
        state: present

